"""Rebuild the stage-by-class coverage matrix from the study-level re-coding and
compare it with the category-default coding of the original pipeline.

Inputs : data/coded_studies.csv (original pipeline output, commit 0d9055c)
         recode_decisions.py    (study-level codes, see codebook.md)
Outputs: recoded_studies.csv, coverage_recoded.json, recode_report.md
"""
import csv, json, os
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ns = {}
exec(open(os.path.join(HERE, "recode_decisions.py"), encoding="utf-8").read(), ns)
DEC = ns["D"]
CLASSES = ["T1", "T2", "T3", "T4", "T5", "T6", "T7"]
STAGES = ["-", "D", "P", "R", "X"]
SELF = {"S058", "S083", "S120", "S134", "S138", "S148", "S160", "S167", "S168"}

old = list(csv.DictReader(open(os.path.join(HERE, "data/coded_studies.csv"), encoding="utf-8")))
assert len(old) == 168 and set(DEC) == {r["sid"] for r in old}

rows = []
for r in old:
    st, cl, t3k, basis, why = DEC[r["sid"]]
    rows.append(dict(sid=r["sid"], title=r["title"], year=r["year"], venue=r["venue"], category=r["category"],
                     survey=int(r["category"].startswith("A")), self_authored=int(r["sid"] in SELF),
                     stage_old=r["stage"], classes_old=r["classes"], stage_new=st, classes_new=cl,
                     t3_kind=t3k, basis=basis, rationale=why))
with open(os.path.join(HERE, "recoded_studies.csv"), "w", newline="", encoding="utf-8") as h:
    w = csv.DictWriter(h, fieldnames=list(rows[0])); w.writeheader(); w.writerows(rows)


def matrix(stage_key, class_key):
    m = defaultdict(Counter); n = Counter(); unspec = Counter()
    for r in rows:
        if r["survey"]:
            n["survey"] += 1; continue
        st = r[stage_key]; n[st] += 1
        cl = r[class_key].split()
        if not cl: unspec[st] += 1
        for c in cl: m[st][c] += 1
    return m, n, unspec


def kappa(a, b):
    """Cohen's kappa for two binary label vectors."""
    n = len(a); po = sum(x == y for x, y in zip(a, b)) / n
    pa, pb = sum(a) / n, sum(b) / n
    pe = pa * pb + (1 - pa) * (1 - pb)
    return (po - pe) / (1 - pe) if pe < 1 else 1.0


m_old, n_old, u_old = matrix("stage_old", "classes_old")
m_new, n_new, u_new = matrix("stage_new", "classes_new")
coded = [r for r in rows if not r["survey"]]

agree = {}
for c in CLASSES:
    a = [int(c in r["classes_old"].split()) for r in coded]
    b = [int(c in r["classes_new"].split()) for r in coded]
    agree[c] = dict(old=sum(a), new=sum(b), kappa=round(kappa(a, b), 2),
                    agreement=round(sum(x == y for x, y in zip(a, b)) / len(a), 3))
all_a = [int(c in r["classes_old"].split()) for r in coded for c in CLASSES]
all_b = [int(c in r["classes_new"].split()) for r in coded for c in CLASSES]
pooled = round(kappa(all_a, all_b), 2)
exact = sum(set(r["classes_old"].split()) == set(r["classes_new"].split()) for r in coded)
stage_changed = [r["sid"] for r in coded if r["stage_old"] != r["stage_new"]]
labels = sorted({r["stage_old"] for r in coded} | {r["stage_new"] for r in coded})
po = sum(r["stage_old"] == r["stage_new"] for r in coded) / len(coded)
pe = sum((sum(r["stage_old"] == s for r in coded) / len(coded)) * (sum(r["stage_new"] == s for r in coded) / len(coded)) for s in labels)
stage_kappa = round((po - pe) / (1 - pe), 2)

t3_design = [r for r in coded if r["stage_new"] == "D" and "T3" in r["classes_new"].split()]
t3_impl_by_stage = Counter(r["stage_new"] for r in coded if r["t3_kind"] == "impl")
t3_policy_by_stage = Counter(r["stage_new"] for r in coded if r["t3_kind"] == "policy")
t7_by_stage = Counter(r["stage_new"] for r in coded if "T7" in r["classes_new"].split())
t4_runtime = [r["sid"] for r in coded if r["stage_new"] == "R" and "T4" in r["classes_new"].split()]
basis = Counter(r["basis"] for r in rows)

out = dict(
    n_total=len(rows), n_surveys=sum(r["survey"] for r in rows), n_coded=len(coded),
    stage_counts_old=dict(n_old), stage_counts_new=dict(n_new),
    matrix_old={s: dict(m_old[s]) for s in STAGES}, matrix_new={s: dict(m_new[s]) for s in STAGES},
    unspecific_new=dict(u_new), unspecific_old=dict(u_old),
    agreement_per_class=agree, pooled_kappa=pooled, exact_set_match=exact,
    stage_changed=stage_changed, stage_kappa=stage_kappa,
    t3_design=[(r["sid"], r["t3_kind"], r["title"][:70]) for r in t3_design],
    t3_impl_by_stage=dict(t3_impl_by_stage), t3_policy_by_stage=dict(t3_policy_by_stage),
    t7_by_stage=dict(t7_by_stage), t4_runtime=t4_runtime, basis=dict(basis),
    self_authored=len(SELF),
)
json.dump(out, open(os.path.join(HERE, "coverage_recoded.json"), "w"), indent=1)

L = ["# Re-coding report (generated by recode.py)", "",
     f"Studies: {out['n_total']} (surveys {out['n_surveys']}, coded for classes {out['n_coded']}); "
     f"coding basis {dict(basis)}; self-authored included studies {len(SELF)}.", "",
     "## Coverage matrix, study-level coding (studies per stage and class; multi-label)", "",
     "| Stage | n | " + " | ".join(CLASSES) + " | unspecific |", "|---|---|" + "---|" * 8]
for s in STAGES:
    L.append(f"| {s} | {n_new[s]} | " + " | ".join(str(m_new[s][c]) for c in CLASSES) + f" | {u_new[s]} |")
L += ["", "## Same matrix, original category-default coding", "",
      "| Stage | n | " + " | ".join(CLASSES) + " |", "|---|---|" + "---|" * 7]
for s in STAGES:
    L.append(f"| {s} | {n_old[s]} | " + " | ".join(str(m_old[s][c]) for c in CLASSES) + " |")
L += ["", "## Agreement between the two coding procedures (non-survey studies)", "",
      "| Class | old count | new count | agreement | Cohen's kappa |", "|---|---|---|---|---|"]
for c in CLASSES:
    a = agree[c]; L.append(f"| {c} | {a['old']} | {a['new']} | {a['agreement']} | {a['kappa']} |")
L += ["", f"Pooled kappa over all study-class pairs: {pooled}. Identical class sets: {exact}/{len(coded)}.",
      f"Stage kappa: {stage_kappa}; stage changed for {len(stage_changed)} studies: {', '.join(stage_changed)}.", "",
      f"T3 at design time: {len(t3_design)} studies, all of kind 'policy': {all(r['t3_kind']=='policy' for r in t3_design)}.",
      f"T3 implementation-flaw studies by stage: {dict(t3_impl_by_stage)}; policy by stage: {dict(t3_policy_by_stage)}.",
      f"T7 by stage: {dict(t7_by_stage)}. Runtime studies with T4: {t4_runtime}."]
open(os.path.join(HERE, "recode_report.md"), "w").write("\n".join(L) + "\n")
print("\n".join(L))
