"""Study-level re-coding decisions (see codebook.md).
sid: (stage, classes, t3_kind, basis, rationale)
basis: 'abstract' or 'title' (no abstract exposed by any index)."""
D = {
"S001": ("D", "T5", "", "abstract", "atomic commitment protocol robust to crash failures and DoS-induced timelock expiry"),
"S002": ("-", "T6", "", "abstract", "new threat: cross-chain bribery contracts manipulating a victim chain's consensus; cost analysis"),
"S003": ("D", "T1", "", "abstract", "formal PoS sidechain construction with a firewall property limiting damage from a compromised sidechain"),
"S004": ("-", "", "", "abstract", "SoK of cross-chain communication protocols (survey)"),
"S005": ("D", "T1 T5 T6", "", "abstract", "TEE exchange against custodial theft, front-running and all-or-nothing fairness"),
"S006": ("D", "T5", "", "abstract", "Tamarin model and formal analysis of HTLC atomic trading"),
"S007": ("D", "T1 T5", "", "abstract", "decentralized exchange protocol removing the trusted third party and enforcing secure trading"),
"S008": ("D", "T5", "", "abstract", "atomic composable cross-chain calls with safety and liveness analysis"),
"S009": ("D", "T5", "", "abstract", "hedging protocols that compensate victims of sore-loser attacks; a defense, not only an attack"),
"S010": ("D", "T1", "", "abstract", "trustless gas-efficient bridge verifying BFT source-chain events instead of trusting relayers"),
"S011": ("D", "T1 T4", "", "abstract", "oracle/relayer separation so that delivery is valid unless both collude"),
"S012": ("-", "T6", "", "title", "cross-chain bribing attacks on PoW chains (attack paper)"),
"S013": ("D", "T1 T7", "", "abstract", "trustless bridge with ZK mixing for private withdrawals"),
"S014": ("D", "T1", "", "abstract", "notary election, margin pool and reputation incentives against notary misconduct"),
"S015": ("D", "T1", "", "title", "quantum multi-signature attestation for cross-chain transactions"),
"S016": ("D", "T5", "", "abstract", "atomic exchange of jointly owned assets resisting collusion"),
"S017": ("D", "T5", "", "abstract", "off-chain channels with fair and atomic cross-chain operations"),
"S018": ("-", "T4", "", "abstract", "light-client jamming attack on IBC reducing cross-chain throughput"),
"S019": ("D", "T4", "", "abstract", "supervision-chain auditing of the integrity of data exchanged across chains"),
"S020": ("D", "T5", "", "abstract", "asset transfer protocol with finality guarantees so assets are not lost in transit"),
"S021": ("R", "T5", "", "abstract", "runtime verification of metric temporal properties of cross-chain protocols"),
"S022": ("D", "T1", "", "abstract", "T-ODAP: trustless permissioned interoperability with game-theoretic participant model"),
"S023": ("-", "", "", "abstract", "multivocal literature review (survey)"),
"S024": ("D", "T1", "", "abstract", "sidechain certificates and committee selection for fast transfers"),
"S025": ("-", "", "", "abstract", "SoK of bridge hacks (survey)"),
"S026": ("D", "T1", "", "abstract", "trust boosting that tolerates insecure participating chains"),
"S027": ("R", "T2 T3", "impl", "abstract", "Xscope: detects inconsistent event parsing, unauthorized unlocking and unrestricted deposits"),
"S028": ("D", "T7", "", "title", "privacy-preserving sidechain transfers for Monero"),
"S029": ("D", "T1", "", "abstract", "zkBridge: succinct proofs of source consensus replace committee honesty"),
"S030": ("-", "", "", "abstract", "survey of cross-chain technologies"),
"S031": ("D", "T7", "", "abstract", "Groth16-based anonymous yet supervisable relay-chain transactions"),
"S032": ("-", "", "", "abstract", "survey of attacks and defenses"),
"S033": ("D", "T1", "", "abstract", "decentralized verification of results computed on another chain instead of trusting it"),
"S034": ("D", "T5", "", "abstract", "cross-chain virtual payment channels with balance security via an intermediary"),
"S035": ("D", "T3", "policy", "abstract", "relay-chain identity governance against forged or impersonated node identities"),
"S036": ("D", "T5", "", "abstract", "TLA+ model checking of IBC protocol requirements"),
"S037": ("D", "T5", "", "title", "formal verification of the burn-to-claim protocol (uniqueness of claims)"),
"S038": ("D", "T1", "", "abstract", "on-demand PoW light client removing trusted-majority bridges"),
"S039": ("D", "T1 T2", "", "abstract", "ZK light client that also fixes security flaws in the Ethereum sync protocol"),
"S040": ("R", "T3", "impl", "abstract", "HighGuard: runtime monitoring of business-logic specifications across chains"),
"S041": ("D", "T5", "", "abstract", "reference framework for IETF SATP: ordered atomic transfer avoiding double spend"),
"S042": ("D", "T1", "", "abstract", "interchain timestamping maximizing slashable safety against provider-chain validator faults"),
"S043": ("-", "", "", "abstract", "survey of blockchain interoperability"),
"S044": ("D", "T5", "", "abstract", "multiparty HTLC atomic swap"),
"S045": ("D", "T7", "", "title", "regulated privacy-preserving cross-chain transactions"),
"S046": ("P", "T3", "impl", "abstract", "mutation-based test generation for faults in cross-chain contract code"),
"S047": ("R", "T1", "", "abstract", "RNN-based dynamic reputation of notaries with decay against malicious notaries"),
"S048": ("D", "T3 T7", "policy", "abstract", "attribute-based cross-chain access control with threshold Paillier hiding policies"),
"S049": ("D", "T1", "", "abstract", "token-transfer framework; reliability via a reputation-weighted validator group"),
"S050": ("D", "T1", "", "abstract", "Alba: trustless bridge verifying off-chain channel states"),
"S051": ("D", "T1 T7", "", "abstract", "incentive contracts with game-theoretic security and ZK privacy for private chains"),
"S052": ("D", "T5", "", "abstract", "atomic cross-chain smart contract invocation"),
"S053": ("D", "T7", "", "abstract", "privacy-preserving yet regulated Monero-Bitcoin cross-chain protocol against linkability"),
"S054": ("-", "", "", "abstract", "systematization of bridge aggregators: architecture, security measures, pricing, latency"),
"S055": ("-", "", "", "abstract", "survey of bridge security"),
"S056": ("R", "T1", "", "title", "trust-model-based selection of the cross-chain consensus committee"),
"S057": ("R", "T1", "", "title", "reputation calculation for notary selection"),
"S058": ("P", "T3", "impl", "abstract", "ChainSniper: ML auditing of vulnerable cross-chain contract code"),
"S059": ("R", "T1 T2 T3", "impl", "abstract", "accounting invariant identifies every known 2021-23 bridge attack"),
"S060": ("R", "", "", "abstract", "graph multi-model fusion for generic abnormal cross-chain transactions"),
"S061": ("D", "T5 T7", "", "abstract", "relay-chain NFT transfer recording resale hashes and encrypting metadata"),
"S062": ("R", "T2", "", "abstract", "transaction-trace analysis detecting fake-deposit attacks"),
"S063": ("R", "", "", "abstract", "Hephaestus: cross-chain model generation for rule-based monitoring of bridge attacks"),
"S064": ("R", "", "", "title", "attack detection framework for cross-chain transactions"),
"S065": ("D", "T3", "policy", "abstract", "decentralized cross-chain identity authentication for IoT"),
"S066": ("D", "T5 T7", "", "abstract", "atomic and privacy-preserving cross-chain asset marketplace"),
"S067": ("D", "T1", "", "abstract", "SNARK-based sidechain construction for IoT chains"),
"S068": ("D", "T4 T5", "", "abstract", "proof of finalization against spoofed blockchain views fed to light nodes or TEEs"),
"S069": ("D", "T3", "policy", "abstract", "multi-user proxy re-signature for cross-chain identity authentication"),
"S070": ("D", "T4", "", "title", "relay-network data interaction with integrity audit"),
"S071": ("R", "T3", "impl", "abstract", "49 incidents plus a graph-mining detector for business-logic attack transactions"),
"S072": ("-", "", "", "abstract", "empirical analysis of Stargate transaction dynamics and exploitation evidence"),
"S073": ("-", "", "", "abstract", "SoK of bridge security (survey)"),
"S074": ("D", "T1", "", "abstract", "generic sidechain with committee selection and threshold signatures"),
"S075": ("P", "T2 T3", "impl", "abstract", "SmartAxe: static detection of missing access control and inconsistent cross-chain semantics"),
"S076": ("-", "", "", "abstract", "SoK of bridge architectural design flaws (survey)"),
"S077": ("-", "", "", "abstract", "SoK of security and privacy of interoperability (survey)"),
"S078": ("R", "T1 T2", "", "abstract", "XChainWatcher: Datalog rules detect the Ronin and Nomad exploits"),
"S079": ("P", "T2 T3", "impl", "abstract", "XGuard: static detection of cross-chain inconsistency behaviors in bridge contracts"),
"S080": ("R", "", "", "abstract", "semantic extraction of cross-chain transactions as a basis for detection"),
"S081": ("D", "T5 T6", "", "abstract", "4-Swap: grief-free and bribery-safe atomic swap"),
"S082": ("-", "T3 T6", "impl", "abstract", "analysis of bridge attacks along economic and implementation dimensions"),
"S083": ("D", "T4", "", "title", "market-based multi-relay architecture for adaptive relaying"),
"S084": ("-", "T5 T6", "", "abstract", "measurement: 308 ledger inconsistencies, arbitrage bots and a liquidity-pool attack"),
"S085": ("D", "T1", "", "abstract", "InterSnap: non-repudiable receipts against fraudulent claims by a foreign network"),
"S086": ("X", "", "", "abstract", "conformance checking triggers automatic pausing within 10 s; no specific attack class"),
"S087": ("R", "", "", "abstract", "BADS: Datalog rules plus LLM triage of generic bridge anomalies"),
"S088": ("P", "T3", "impl", "abstract", "BridgeGuard: symbolic dataflow detection of external-interaction and access-control flaws"),
"S089": ("R", "", "", "abstract", "BridgeShield: heterogeneous-graph detection of generic bridge attacks"),
"S090": ("R", "", "", "title", "information-flow-graph detection of bridge attacks"),
"S091": ("-", "", "", "abstract", "comparative metrics-based security analysis of bridges; no specific class"),
"S092": ("D", "T7", "", "abstract", "conditional privacy with unlinkable multi-chain transactions"),
"S093": ("R", "", "", "abstract", "ConneX: LLM-assisted pairing of cross-chain transactions for later analysis"),
"S094": ("D", "T7", "", "abstract", "lattice-based designated-verifier proxy signature for private medical data sharing"),
"S095": ("P", "T3", "impl", "title", "limits of static analysis for cross-chain contracts"),
"S096": ("D", "T5", "", "abstract", "cross-chain micropayment channels with chain-relay synchronization"),
"S097": ("D", "T1", "", "abstract", "DeCross: accountability against colluding and adaptively corrupted participants"),
"S098": ("-", "T5", "", "abstract", "double-spending vectors amplified in cross-chain settings"),
"S099": ("D", "T5 T7", "", "abstract", "payment-channel hub with unlinkability resisting the abort attack"),
"S100": ("D", "T5", "", "abstract", "Isabelle/HOL proof that a fail-safe bridge design keeps both chains balanced"),
"S101": ("-", "", "", "abstract", "broad systematization of 23 attack vectors across all layers"),
"S102": ("D", "T1 T5 T7", "", "abstract", "IvyCross: TEE interoperability with incentives, race-free concurrency and privacy"),
"S103": ("R", "", "", "abstract", "two-page anomaly-detection abstract; no class named"),
"S104": ("D", "T3 T7", "policy", "abstract", "multi-authority ABE with delegated access for cross-chain data sharing"),
"S105": ("D", "T2 T7", "", "abstract", "aggregated ZK proofs and secure block verification for batch transfers"),
"S106": ("D", "T5 T7", "", "abstract", "P2C2T: atomic and unlinkable cross-chain transfer"),
"S107": ("D", "T5 T7", "", "abstract", "Pace: privacy-preserving atomic swaps on public chains"),
"S108": ("-", "T2 T4", "", "abstract", "phantom events: forged logs mislead bridges and off-chain services"),
"S109": ("-", "", "", "abstract", "measurement dataset of 80M cross-chain transactions"),
"S110": ("D", "T7", "", "title", "privacy-preserving notary transfers with ZK proofs"),
"S111": ("D", "T4 T5", "", "abstract", "data-interoperability protocols resisting withholding and censorship"),
"S112": ("D", "T7", "", "title", "relay-chain framework with privacy and auditability"),
"S113": ("D", "T4 T5", "", "abstract", "SightCVC: channels with authentic chain information for dispute resolution"),
"S114": ("-", "", "", "abstract", "SoK of 2022-23 bridge hacks (survey)"),
"S115": ("-", "T6", "", "abstract", "cross-chain sandwich attacks exploiting source-chain events"),
"S116": ("D", "T4", "", "abstract", "consistency auditing of dynamic data exchanged across chains"),
"S117": ("-", "", "", "abstract", "heuristic tracing of Ethereum-Polygon transfers; no attack class"),
"S118": ("R", "T6", "", "abstract", "ABCTracer: bi-directional tracing against laundering through bridges"),
"S119": ("D", "T1 T4", "", "abstract", "random-sampling light clients with permissionless relayers"),
"S120": ("R", "T3", "impl", "abstract", "VeriBridge: graph anomaly detection enriched with static vulnerability findings"),
"S121": ("D", "T5", "", "abstract", "PipeSwap: forces timely secret release against double-claiming"),
"S122": ("-", "T6", "", "title", "laundering through a bridge after the Harmony hack"),
"S123": ("-", "T6", "", "abstract", "chain-hopping and suspicious flows on Wormhole"),
"S124": ("R", "", "", "abstract", "XChainDataGen: open cross-chain transaction dataset generator"),
"S125": ("R", "", "", "title", "Brigade: defense evaluated against real-world bridge exploits; title names no class"),
"S126": ("D", "T7", "", "abstract", "verifiable privacy-preserving cross-chain protocol for vehicle edge computing"),
"S127": ("R", "", "", "title", "data-analytics anomaly detection for bridges"),
"S128": ("D", "T7", "", "abstract", "notary framework with lattice identity-based ring signatures for anonymity"),
"S129": ("D", "T7", "", "title", "regulatory privacy protection for cross-chain anonymous payments"),
"S130": ("-", "T6", "", "abstract", "contagion of bridge exploits through bridged collateral"),
"S131": ("-", "T6", "", "abstract", "measurement of cross-chain arbitrage as MEV"),
"S132": ("X", "T6", "", "title", "tracking cryptocurrency laundering across chains"),
"S133": ("D", "T7", "", "title", "identity privacy via oblivious transfer and key agreement"),
"S134": ("P", "T2 T3", "impl", "abstract-web", "CrossGuard: few-shot detection of contract vulnerabilities incl. verification paths (abstract via publisher snippet)"),
"S135": ("R", "T6", "", "abstract", "clustering framework detecting Sybil airdrop farming in cross-chain transactions"),
"S136": ("D", "T1", "", "abstract", "EquiLink: TEE semi-custodial bridge reducing custodian trust"),
"S137": ("P", "T2 T4", "", "abstract", "EventSpec: event-semantic defects that mislead off-chain bridges"),
"S138": ("P", "", "", "title", "evolutionary exploit generation for bridges; title names no class"),
"S139": ("-", "T6", "", "abstract", "liquidity exhaustion attacks on intent-based bridge solvers"),
"S140": ("P", "T3 T4 T5", "impl", "abstract", "BridgeFuzz: balance mismatches, protocol errors and off-chain DoS bugs"),
"S141": ("D", "T5", "", "abstract", "GumSwap: griefing-free universal multi-party swaps"),
"S142": ("D", "T1 T4", "", "abstract", "hybrid relay architecture with probabilistic trust coordination"),
"S143": ("P", "T3", "impl", "abstract", "IntentFuzz: invariant-violation fuzzing of intent-bridge contracts"),
"S144": ("D", "T7", "", "abstract", "linkable threshold ring adaptor signatures for private transfers"),
"S145": ("X", "", "", "abstract", "decentralized cross-chain kill switch; no specific class"),
"S146": ("D", "T1", "", "abstract", "Mercury: TEE exchange removing trusted participants"),
"S147": ("-", "T6", "", "abstract", "liquidity poisoning of multihop cross-chain arbitrage"),
"S148": ("D", "", "", "title", "lightweight verifiable interoperability for edge networks; title names no class"),
"S149": ("R", "T1", "", "abstract", "behavior-driven reputation with auditor committees for cross-chain consensus nodes"),
"S150": ("D", "T3", "policy", "title", "service-level access control for interoperable blockchains"),
"S151": ("D", "T5", "", "abstract", "batch scriptless atomic swaps"),
"S152": ("D", "T5", "", "title", "securing HTLC with a trusted middleman"),
"S153": ("D", "T5 T7", "", "abstract", "ShiftHub: atomic and unlinkable m-to-1 transfers"),
"S154": ("-", "T6", "", "abstract", "speculative oracle extractable value across Layer-2 chains"),
"S155": ("-", "T5", "", "abstract", "stalled cross-chain transactions trapping funds (liveness)"),
"S156": ("-", "T6", "", "abstract", "economic consequences of bridge liquidity across 16 bridges"),
"S157": ("X", "T6", "", "abstract", "AMLGuard: semantic tracking of laundered funds after incidents"),
"S158": ("D", "T1 T7", "", "abstract", "VeCroToken: zk-SNARK private transfers reducing relay trust"),
"S159": ("D", "T5 T7", "", "abstract", "XPCH: privacy-preserving payment-channel-hub transfers"),
"S160": ("D", "T5 T7", "", "title", "zk-HTLC: formally verified defense against linkability of HTLC transfers"),
"S161": ("D", "T1", "", "abstract", "XCLAIM: collateralized vaults for trustless backed assets"),
"S162": ("-", "", "", "abstract", "SoK of DeFi attacks (survey)"),
"S163": ("-", "", "", "abstract", "SoK of DeFi (survey)"),
"S164": ("-", "", "", "abstract", "survey of interoperability"),
"S165": ("-", "", "", "abstract", "survey of interoperability"),
"S166": ("-", "", "", "abstract", "overview of cross-chain mechanisms (survey)"),
"S167": ("R", "T1", "", "abstract", "CrossTrust-IoT: RL trust ranking with Gini control against influence concentration"),
"S168": ("D", "T1 T3 T7", "policy", "abstract-web", "DAVE-CC: threshold authorities, access control and selective disclosure (abstract via publisher snippet)"),
}
